modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="phoenix"
version="ASH-0.1.2B"
displayName="Project Phoenix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/phoenix-project"
credits="Hohserg, Krokodil, Liahim, Landex and you, for help me"
authors="WildTan"
description='''This mod adds more content to the end. In the begining it will be your good old end. But when you find 4 temples it will change. There are two new biomes and 1 new mob(in plans there would be 4 new mobs, but now only 1). It is second stage - redo. There will be 4 in the plans: death, redo, rebirth, air. The world, mobs, dragon fighting will change and supplement from stage to stage. This is a technical modification, so the main mechanics are technologies. For smetri, this is ceramics, for edits, this is modifying ceramics and working with plants, for rebirth, this is working with living mobs, up to creating your own species, for air, this is working with imzers, here you will create your own worlds. Let the story begin! '''
logoFile="icon.png"
[[dependencies.phoenix]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"